#      - "config --json API.HTTPHeaders.Access-Control-Allow-Origin '[\"*\"]'"
#      - "config --json API.HTTPHeaders.Access-Control-Allow-Methods '[\"GET\", \"POST\"]'"

version: '3'

services:
  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs
    restart: unless-stopped
    ports:
      - "0.0.0.0:8080:8080"  # IPFS Gateway Port
    volumes:
      - /root/ipfs/data:/data/ipfs
    command:
      - "daemon"
      - "--migrate=true"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - '5001:5001'
    volumes:
      - '/root/ipfs/default.conf:/etc/nginx/conf.d/default.conf:ro'
      - '/root/ipfs/htpasswd:/htpasswd:ro'
      - '/root/ipfs/fullchain.pem:/fullchain.pem'
      - '/root/ipfs/privkey.pem:/privkey.pem'
    restart: unless-stopped

